##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
# esempio di client e server TCP, IPv6 only 
#
##################################################

all: TCPServer6 TCPClient6 TCPServer6_2


TCPServer6: TCPServer6.c
	gcc -o TCPServer6 TCPServer6.c

TCPServer6_2: TCPServer6_2.c
	gcc -o TCPServer6_2 TCPServer6_2.c

TCPClient6: TCPClient6.c
	gcc -o TCPClient6 TCPClient6.c

clean:
	rm TCPServer6 TCPClient6 TCPServer6_2

##################################################