##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes per la 
# manipolazione degli indirizzi Internet
#
##################################################

all: NameLookup 

NameLookup: HostnameResolution.c
	gcc -o NameLookup HostnameResolution.c

clean:
	rm NameLookup 

##################################################
