##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
# Socket options 
#
#
##################################################

all: Options 

Options: DefaultOptions.c
	gcc -o Options DefaultOptions.c

clean:
	rm -f Options 
##################################################